name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Run pylint
      run: |
        pylint *.py

    - name: Run qq.py
      run: |
        python qq.py "List files in current directory"
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
